package com.its.gestionepagamentirestclient.config;

import org.springframework.amqp.core.AmqpAdmin;
import org.springframework.amqp.core.Binding;
import org.springframework.amqp.core.BindingBuilder;
import org.springframework.amqp.core.DirectExchange;
import org.springframework.amqp.core.Queue;
import org.springframework.amqp.rabbit.config.SimpleRabbitListenerContainerFactory;
import org.springframework.amqp.rabbit.connection.ConnectionFactory;
import org.springframework.amqp.rabbit.core.RabbitAdmin;
import org.springframework.amqp.rabbit.core.RabbitTemplate;
import org.springframework.amqp.support.converter.JacksonJsonMessageConverter;
import org.springframework.amqp.support.converter.MessageConverter;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * RabbitMQ topology for the payment service.
 *
 * <p>This service consumes payment requests from the orders exchange and
 * publishes payment processing results to the payment results exchange.</p>
 */
@Configuration
public class RabbitMQConfig {

    public static final String PAYMENT_QUEUE = "queue-payment";
    public static final String ORDERS_EXCHANGE = "exchange-orders";
    public static final String PAYMENT_REQUEST_ROUTING_KEY = "order.payment.request";

    public static final String PAYMENT_RESULTS_EXCHANGE = "exchange-payment-results";
    public static final String PAYMENT_RESULTS_ROUTING_KEY = "payment.status.updated";

    /**
     * Queue that receives payment requests generated by the order service.
     *
     * @return durable payment request queue
     */
    @Bean
    public Queue paymentQueue() {
        return new Queue(PAYMENT_QUEUE, true);
    }

    /**
     * Exchange used by the order service to publish payment requests.
     *
     * @return direct exchange for order commands
     */
    @Bean
    public DirectExchange ordersExchange() {
        return new DirectExchange(ORDERS_EXCHANGE);
    }

    /**
     * Binding that routes payment requests to the payment queue.
     *
     * @return binding between orders exchange and payment queue
     */
    @Bean
    public Binding paymentQueueBinding() {
        return BindingBuilder.bind(paymentQueue())
                .to(ordersExchange())
                .with(PAYMENT_REQUEST_ROUTING_KEY);
    }

    /**
     * Exchange used to publish the result of payment processing.
     *
     * @return direct exchange for payment result events
     */
    @Bean
    public DirectExchange paymentResultsExchange() {
        return new DirectExchange(PAYMENT_RESULTS_EXCHANGE);
    }

    /**
     * AMQP admin used to declare queues, exchanges, and bindings on broker startup.
     *
     * @param connectionFactory RabbitMQ connection factory
     * @return admin bean
     */
    @Bean
    public AmqpAdmin amqpAdmin(ConnectionFactory connectionFactory) {
        return new RabbitAdmin(connectionFactory);
    }

    /**
     * JSON converter used by senders and listeners.
     *
     * @return Jackson-based message converter
     */
    @Bean
    public MessageConverter jsonMessageConverter() {
        return new JacksonJsonMessageConverter();
    }

    /**
     * RabbitTemplate configured for JSON payloads.
     *
     * @param connectionFactory RabbitMQ connection factory
     * @param jsonMessageConverter JSON converter
     * @return configured RabbitTemplate
     */
    @Bean
    public RabbitTemplate rabbitTemplate(ConnectionFactory connectionFactory,
                                         MessageConverter jsonMessageConverter) {
        RabbitTemplate template = new RabbitTemplate(connectionFactory);
        template.setMessageConverter(jsonMessageConverter);
        return template;
    }

    /**
     * Listener container factory configured with JSON message conversion.
     *
     * @param connectionFactory RabbitMQ connection factory
     * @param jsonMessageConverter JSON converter
     * @return listener container factory
     */
    @Bean
    public SimpleRabbitListenerContainerFactory rabbitListenerContainerFactory(
            ConnectionFactory connectionFactory,
            MessageConverter jsonMessageConverter) {
        SimpleRabbitListenerContainerFactory factory = new SimpleRabbitListenerContainerFactory();
        factory.setConnectionFactory(connectionFactory);
        factory.setMessageConverter(jsonMessageConverter);
        return factory;
    }
}