spring.application.name=gestionepagamentirestclient

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

server.servlet.context-path=${CONTEXT_PATH}
server.port=8080

order.service.url=${ORDER_SERVICE}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

spring.config.import=optional:configtree:/run/secrets/

aws.s3.bucket-name=${BUCKET_NAME}
aws.s3.region=${AWS_REGION}
app.s3.prefix=p.rebong